### ISSUE TITLE
Parse .opcode files and instantiate CodeWithUnknown

### ISSUE THREAD

**Issue by allegroCoder** [tuura/scenco#14]
Parse .opcode files and instantiate `CodeWithUnknown` in the format defined in `Code.hs`. This is one of  the input of the function for checking the correctness of the final encoding.

**Comment by allegroCoder** [comment]
@snowleopard could you help me with the function `convertOpcodes`, please:

```haskell
parseCustomOpcode :: FilePath -> IO ([CodeWithUnknowns])
parseCustomOpcode opcodePath = do
    fileContent <- readFile opcodePath
    let fileLines = lines fileContent
        bitLength = last fileLines
        customOpcodes = reverse $ tail $ reverse fileLines
        codes = convertOpcodes (last customOpcodes)
    return codes

convertOpcodes :: [String] -> [CodeWithUnknowns]
convertOpcodes (op:opcodes) = convertOpcode op

convertOpcode :: String -> CodeWithUnknowns
convertOpcode (x:xs)
    | x == "0"       = used False
    | x == "1"       = used True
    | x == "X"       = unknown
    | x == "-"       = unused
    | x == otherwise = error $ "Custom opcodes file contains wrong character"
```

`convertOpcodes` is supposed to take a list of strings in the following format:
```
/     = all the bits are Unknown
XXXX  = same as above
0X1X  = second and fourth bits are Unknown
X00-  = First bit is unknown, fourth unused
0000  = all bits used here
```
`bitLength` is known in advance since it is present in the last line of the file. I take this with the line: `customOpcodes = reverse $ tail $ reverse fileLines`

**Comment by allegroCoder** [comment]
I found another way to do this, mapping a function to each element of the list of string.

```haskell
parseCustomOpcode :: FilePath -> IO ()
parseCustomOpcode opcodePath = do
    fileContent <- readFile opcodePath
    let fileLines = lines fileContent
        bitLength = last fileLines
        customOpcodes = reverse $ tail $ reverse fileLines
    forM_ customOpcodes $ \s -> do
        forM_ s convertBit

convertBit :: Char -> Bit (BoolWithUnknowns)
convertBit x
    | x == '0'       = used False
    | x == '1'       = used True
    | x == 'X'       = unknown
    | x == '-'       = unused
    | x == otherwise = error $ "Custom opcodes file contains wrong character"

Unfortunately, I cannot make this work either. Also because in this case I guess that I need to reconstruct each opcode using the `zip` functions multiple times, concatenating `bitLength` elements at a time.
```

**Comment by snowleopard** [comment]
@allegroCoder Let's start with a simpler task. As I understand, even `convertBit` is currently incorrect. So why don't you implement it in isolation first and test that it works correctly? We can then proceed to other more complex functions. So, I think here is a correct implementation (also renaming to `readBit`):
```haskell
readBit :: Char -> Bit BoolWithUnknowns
readBit x
    | x == '0'       = known False
    | x == '1'       = known True
    | x == 'X'       = unknown
    | x == '-'       = unused
    | x == otherwise = error $ "readBit: character '" ++ x ++ "' is not recognised."
```
Does this work for you? 

The next step is to implement `readCode`:
```haskell
readCode :: String -> CodeWithUnknowns
readCode = map readBit
```
Basically, to read a code from a `String`, you need to apply `readBit` to each character. Is this what you want? (Reading `String`s from a file should be fairly straightforward and should be done separately.)

**Comment by allegroCoder** [comment]
Thanks @snowleopard :+1: 

Below the final implementation. Now I can test code correctness and then automate everything with travis and cabal!

```haskell
parseCustomOpcode :: FilePath -> IO ([CodeWithUnknowns])
parseCustomOpcode opcodePath = do
    fileContent <- readFile opcodePath
    let fileLines = lines fileContent
        bitLength = last fileLines
        customOpcodes = reverse $ tail $ reverse fileLines
    return $ map readCode customOpcodes

readCode :: String -> CodeWithUnknowns
readCode = map readBit

readBit :: Char -> Bit BoolWithUnknowns
readBit x
    | x == '0'       = known False
    | x == '1'       = known True
    | x == 'X'       = unknown
    | x == '-'       = unused
    | otherwise      = error $ "readBit: character '" ++ show x ++ "' is not recognised."
```

**Comment by snowleopard** [comment]
I think you shouldn't mix reading from a file and parsing the codes. The following function should be much more reusable (also renaming all `opcode` to `code` for generality):
```haskell
readCodes :: [String] -> [CodeWithUnknowns]
readCodes = map readCode
```
Then if you want to read this from a file, why don't you do the following:
```haskell
do
    contents <- lines <$> readFile opcodePath
    let codeLength = length $ head contents
        codes      = readCodes contents
```
I am not sure what were you doing in the code with all those `reverse` and `last` bits.

**Comment by allegroCoder** [comment]
Thanks @snowleopard , I think we can close this one. `reverse` and `last` were useful because the bit length of the opcodes was present in the last line of the `.opcode` files. I removed this now.
