### ISSUE TITLE
Segmentation fault 11 on Mac OS X

### ISSUE THREAD

**Issue by allegroCoder** [tuura/scenco#18]
There is an issue running `SCENCO` with Mac OS X. I tried to understand what it is related to, but I could not.

Sometimes (only under Mac OS X), the program breaks in the middle of the execution returning "segmentaiton fault 11". Firstly, I thought it was a problem related to running out of the stack memory, hence I allocated all the variables in the heap dynamically. I also got rid of most of the defines there were before in `SCENCO` (`scenariosLimit` for instance).

After many attempts together with @jrbeaumont , we did not reach a solution yet. He has been helping me a lot, trying to debug the tool in his Mac.

Unfortunately, this might be a subtle Mac OS bug (links below). Considering the foreign interface with C++/C, I am not sure if something goes wrong, during the compilation/building of the binary.

http://stackoverflow.com/questions/14420712/haskell-segmentation-fault-with-factorial
http://stackoverflow.com/questions/5981324/ghci-segfault-with-simple-math
https://github.com/sol/doctest/issues/11

`SCENCO` works either under Windows and Linux.

**Comment by snowleopard** [comment]
> Sometimes (only under Mac OS X), the program breaks in the middle of the execution returning "segmentaiton fault 11"

Can you make this bug 100% reproducible? What is the exact testing scenario? Having such a test would be helpful so that we could be sure in future that a fix does the job.

**Comment by allegroCoder** [comment]
I did not manage to make the bug always reproducible. Also without going through the synthesis phase (where ABC is involved), sometimes the flow stops, others it does not.

Moreover, it's difficult for me to test this since I don't have a Mac. @jrbeaumont, maybe we could meet one day and try to debug this properly together?

**Comment by jrbeaumont** [comment]
I made some attempt to debug this yesterday, or at least find the area of code which is affecting it, but unfortunately, I have not found out too much.

I will continue working on it, but I am happy to meet to try and debug this together. I am free all day tomorrow.

**Comment by allegroCoder** [comment]
Thanks a lot. I will send you a message tomorrow then. :+1:

**Comment by allegroCoder** [comment]
Problem solved. Thanks a lot @jrbeaumont for your support. A `segmentation fault` was generated in the `load_graphs_opcodes` function due to a variable, passed as parameter from Haskell, which was overwritten wrongly.

**Comment by snowleopard** [comment]
@allegroCoder @jrbeaumont Well done! :+1:
