### ISSUE TITLE
Encoding interface between Haskell <=> C++

### ISSUE THREAD

**Issue by allegroCoder** [tuura/scenco#6]
How to import an array of strings from a c++ function. The array contains all the opcodes associated to the graphs in the form "01", "-" (representing a don't use bit)

@snowleopard let me know if you have a quick suggestion. I will explore how to do it myself though.

**Comment by snowleopard** [comment]
First of all, I would suggest to avoid using strings for the representation. Instead of a string, we should use an array of integer values from an enumeration type: `ZERO`, `ONE`, `DONT_USE`, or something similar. Let's try to import one such encoding first and then see how to go further!

**Comment by snowleopard** [comment]
We should try to match the representation we have in Haskell, with the one we have in C++. That should simplify the interface. This means that we probably need another constant `UNKNOWN`.

**Comment by allegroCoder** [comment]
I tried to keep the old SCENCO structure so far. It won't be difficult to modify the internal c++ structure to allow two different types for the encoding: the one in input accepting (ONE - ZERO - UNKNOWN - DONT_USE), and the one for the outuput accepting (ONE - ZERO - DONT_USE).

In order not to allow any inconsistencies for the final opcodes.

**Comment by allegroCoder** [comment]
So far I would close the issue. We might re-open it in the case the interface will need any modifications.
